const POST_USER_DATA = "POST_USER_DATA";
const USER_UPDATE = "USER_UPDATE";
const POST_USER_TOKEN = "POST_USER_TOKEN";
const CASES = "CASES";
const SET_CONFIG = "SET_CONFIG";
const LOGOUT_USER_DATA = "LOGOUT_USER_DATA";

export {
  POST_USER_DATA,
  USER_UPDATE,
  POST_USER_TOKEN,
  CASES,
  SET_CONFIG,
  LOGOUT_USER_DATA
};
